name: examples.registration_form

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  angular:
  angular_components: ^0.14.0-alpha
  # No strict dependencies, we always use dependency_overrides.
  angular_forms:

dev_dependencies:
  build_runner: ^1.6.1
  build_test: ^0.10.2+5
  build_web_compilers: ^2.1.1
  sass_builder: ^2.0.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  #angular:
  #  path: ../../angular
  #angular_ast:
  #  path: ../../angular_ast
  #angular_compiler:
  #  path: ../../angular_compiler
  #angular_forms:
  #  path: ../../angular_forms
